### ISSUE TITLE
Fix coding style

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#285]
#265 has introduced loads of underscored_variable_names which should be written as lowerCamelCase according to [our coding standards](https://github.com/UltimateHackingKeyboard/firmware/blob/master/CONTRIBUTING.md). Please fix this, and let's adhere to our coding standards as much as possible.

**Comment by kareltucek** [comment]
Oops. I will need to take care of reverse merge of the functionality first. Sorry for the inconvenience!

**Comment by daenney** [comment]
Since there's already a `.clang-format` in this repository, why not have CI check this on PRs?

Something like:

```yaml
addons:
  apt:
    sources:
      - llvm-toolchain-xenial-10
    packages:
      - clang-format-10
```
And then as one of the jobs

```
find . -type f \( -name '*.c' -o -name '*.h' \) -print0 | xargs -r0 clang-format
```
